suzuki-shunsuke/tfcmt

- COMPARED_WITH_TFNOTIFY.md
- notifier/github/notify.go
- terraform/template.go
- terraform/template_test.go
BREAKING CHANGE: change the behavior of destroy warning
---
tfcmt posts a deletion warning comment as the other comment.
tfcmt posts only one comment whose template is `when_destroy.template`.
```yaml
when_destroy:
label: "destroy"
label_color: "d93f0b"  # red
template: |
{{ .Title }}
[CI link]( {{ .Link }} )
This plan contains **resource deletion**. Please check the plan result very carefully!
{{ .Message }}
{{if .Result}}
<pre><code>{{ .Result }}
</pre></code>
{{end}}
<details><summary>Details (Click me)</summary>
<pre><code>{{ .Body }}
</pre></code></details>
```
And the default title of destroy warning is changed to `## :warning: Resource Deletion will happen :warning:`.
> feat: change the behavior of destroy warning

- notifier/github/notify.go
If it failed to update labels, the comment isn't posted.
When it failed update labels, the command exits immediately and exit code isn't 0.
When it failed update labels, output error logs but the process continues.
If it succeeds to post a comment, the exit code depends on the result of terraform command.
> fix: post a comment even if it failed to update labels

- COMPARED_WITH_TFNOTIFY.md
- notifier/github/notify.go
* docs: fix a document. #35 has no breaking change
* fix: fix a typo
> docs: fix document

- COMPARED_WITH_TFNOTIFY.md
- README.md
- notifier/github/notify.go
- terraform/parser.go
- terraform/template.go
As a summary of the result of `terraform plan`, it is convenient to show a list of resource paths.
* `.CreatedResources`: a list of created resource paths ([]string)
* `.UpdatedResources`: a list of updated resource paths ([]string)
* `.DeletedResources`: a list of deleted resource paths ([]string)
* `.ReplacedResources`: a list of replaced resource paths ([]string)
```yaml
{{if .CreatedResources}}
* Create
{{- range .CreatedResources}}
* {{.}}
{{- end}}{{end}}{{if .UpdatedResources}}
* Update
{{- range .UpdatedResources}}
* {{.}}
{{- end}}{{end}}{{if .DeletedResources}}
* Delete
{{- range .DeletedResources}}
* {{.}}
{{- end}}{{end}}{{if .ReplacedResources}}
* Replace
{{- range .ReplacedResources}}
* {{.}}
{{- end}}{{end}}
```
```
* Create
* null_resource.foo
* Update
* mysql_database.bar …
```
> feat: add template variables CreatedResource, UpdatedResources, DeletedResources and ReplacedResources

- COMPARED_WITH_TFNOTIFY.md
- README.md
- config/config_test.go
- example-use-raw-output.tfcmt.yaml
- example-with-destroy-and-result-labels.tfcmt.yaml
- example.tfcmt.yaml
- main.go
- notifier/github/notify.go
- terraform/template.go
- terraform/template_test.go
We added more general option `-var` and template variable `Vars`, so the `message` opiton isn't needed.
We have never used `messsage` option and variable, so I decided to remove them.
> remove `message` option and template variable `Message`

- COMPARED_WITH_TFNOTIFY.md
- README.md
- config/config_test.go
- example-use-raw-output.tfcmt.yaml
- example-with-destroy-and-result-labels.tfcmt.yaml
- example.tfcmt.yaml
- main.go
- notifier/github/client.go
- notifier/github/github_test.go
- notifier/github/notify.go
- notifier/github/notify_test.go
- terraform/template.go
- terraform/template_test.go
BREAKING CHANGE: `--title` and `--destroy-warning-title` options and template variable "title" are removed
We introduced more general option `-var` and template variable `.Vars`,
so the `--title` and `--destroy-warning-title` options aren't needed.
> fix: remove title and destroy-warning-title options and template variable ".Title"

- COMPARED_WITH_TFNOTIFY.md
- config/config.go
- main.go
When a configuration file path isn't specified and it isn't found, tfcmt works with the default configuration.
> feat: make the configuration file optional

- COMPARED_WITH_TFNOTIFY.md
- main.go
- terraform/template.go
BREAKING CHANGE: the variable "target" is added to default template and default label name
This is useful for Monorepo. By setting `target`, we can distinguish the comment and label of each service.
When this variable isn't set, this is just ignored.
> feat: add the variable "target" to default template and default label name

- COMPARED_WITH_TFNOTIFY.md
- config/config.go
- main.go
- notifier/github/client.go
- notifier/github/notify.go
- terraform/template.go
- terraform/template_test.go
Close #50 
ex.
```yaml
templates:
title: "## Plan Result ({{.Vars.target}})"
terraform:
plan:
template: |
{{template "title" .}}
```
The following builtin templates are defined. We can override them.
* plan_title
* apply_title
* result
* updated_resources
* deletion_warning
> feat: add templates config

- COMPARED_WITH_TFNOTIFY.md
- config/config.go
- config/config_test.go
- main.go
Close #55 
* -owner
* -repo
* -pr
* -sha
* -build-url
mercari/tfnotify gets these parameters from only environment variables, so we don't use mercari/tfnotify on the platform which mercari/tfnotify doesn't support.
On the other hand, tfcmt supports to specify these parameters by command-line options, so we can use tfcmt anywhere.
ex.
```
$ tfcmt -owner suzuki-shunsuke -repo tfcmt -pr 3 -- terraform plan
```
> feat: add command-line options about ci

- COMPARED_WITH_TFNOTIFY.md
- config/config.go
- error.go
- go.mod
- go.sum
- main.go
- notifier/github/notify.go
Close #56 
ex.
```
$ tfcmt --log-level debug plan -- terraform plan
```
```yaml
---
log:
level: debug
```
Note that there is no debug log yet.
> feat: add log level option and log.level configuration and output structured log with logrus

- COMPARED_WITH_TFNOTIFY.md
- config/config.go
- go.mod
- go.sum
- main.go
- notifier/github/client.go
- notifier/github/comment.go
- notifier/github/notify.go
- notifier/github/user.go
Close #47 
Old comments of `terraform plan` are hidden by default.
tfcmt hides old comments of `terraform plan` by default.
Comments of `terraform apply` aren't hidden.
When tfcmt posts a comment, tfcmt injects a HTML comment `\n` to the suffix.
And before posting the comment, tfcmt gets a list of pull request comments and selects comments which will be hidden.
Comments which match all of the following conditions are hidden.
* comment author is same as tfcmt's authenticated user. When it failed to get the authenticated user login, this condition is ignored
* tfcmt's authenticated user has a permission to hide the comment
* comment includes ``
After it succeeds to post a comment, tfcmt hides them.
If it failed to post a comment, comments aren't hidden.
We can disable this feature by …
> feat: support to hide old comments

- COMPARED_WITH_TFNOTIFY.md
- README.md
- config/config_test.go
- example-use-raw-output.tfcmt.yaml
- example-with-destroy-and-result-labels.tfcmt.yaml
- example.tfcmt.yaml
- notifier/github/notify.go
- terraform/template.go
- terraform/template_test.go
BREAKING CHNAGE: the template variable `Body` is removed.
Please replace `Body` into `CombinedOutput`.
`CombinedOutput` includes both the standard output and standard error output.
`tfcmt` parsed only the standard output and ignored standard error output, so it failed to parse the error result.
> fix: remove the template variable Body

- COMPARED_WITH_TFNOTIFY.md
- config/config.go
- go.mod
- go.sum
- main.go
- notifier/github/client.go
- notifier/github/comment.go
- notifier/github/notify.go
- notifier/notifier.go
- terraform/parser.go
Embed metadata into comment with [github-comment-metadata](https://github.com/suzuki-shunsuke/github-comment-metadata).
tfcmt doesn't hide comments anymore.
Instead, we can hide comments with [github-comment's hide command](https://github.com/suzuki-shunsuke/github-comment).
> feat: embed github-comment metadata

- COMPARED_WITH_TFNOTIFY.md
- README.md
- docs/CONFIGURATION.md
- docs/ENVIRONMENT_VARIABLE.md
- example-with-destroy-and-result-labels.tfcmt.yaml
- example.tfcmt.yaml
- examples/getting-started/README.md
- go.mod
- go.sum
- pkg/cli/var.go
- pkg/config/complement.go
- pkg/config/complement_envsubst.go
- pkg/config/complement_template.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/controller/controller.go
- pkg/domain/complement.go
- pkg/platform/ci.go
- pkg/platform/generic.go
Close #57 
The configuration `ci` is changed.
AS IS
```yaml
ci:
owner: suzuki-shunsuke
repo: tfcmt
```
TO BE
```yaml
ci:
owner:
- type: envsubst
value: suzuki-shunsuke
repo:
- type: envsubst
value: tfcmt
```
> feat: support to complement options with any environment variables

- docs/CONFIGURATION.md
- docs/ENVIRONMENT_VARIABLE.md
- pkg/config/complement.go
- pkg/config/config_test.go
- pkg/controller/controller.go
- pkg/platform/ci.go
- pkg/platform/generic.go
e.g.
```yaml
ci:
vars: # ci.vars supports dynamic values using "template" or "envsubst"
yoo: # the variable "yoo" is added to ".Vars"
- type: template
value: '{{env "YOO"}}'
vars: # "vars" only supports static value
foo: foo
```
> feat: add vars to ci

- docs/CONFIGURATION.md
- go.mod
- go.sum
- pkg/notifier/github/notify.go
- pkg/terraform/parser.go
- pkg/terraform/parser_test.go
- pkg/terraform/template.go
Close #103 
The following variables are added.
* ChangedResult
* ChangeOutsideTerraform
* Warnings
e.g.
```
Warning: "silenced": [DEPRECATED] Use the Downtime resource instead.
with datadog_monitor.foo_success_rate,
on foo.tf line 30, in resource "datadog_monitor" "foo_success_rate":
30: resource "datadog_monitor" "foo_success_rate" {
(and one more similar warning elsewhere)
Warning: "thresholds": [DEPRECATED] Define `monitor_thresholds` list with one element instead.
with datadog_monitor.foo_success_rate,
on foo.tf line 30, in resource "datadog_monitor" "foo_success_rate":
30: resource "datadog_monitor" "foo_success_rate" {
(and 7 more similar warnings elsewhere)
```
```yaml
when_destroy:
template: |
{{template "plan_title" .}}
{{if .Link}}[CI link]({{.Link}}){{end}}
{{template …
```
> feat: add template variables

- pkg/config/config.go
- pkg/controller/controller.go
- pkg/notifier/github/client.go
- pkg/notifier/github/notify.go
Close #108
tfcmt embedds the metadata into the comment to hide the comment by the metadata.
With tfcmt v1, all variables are embedded into the comment, but sometimes this behaviour is undesirable.
With tfcmt v2, only variables specified by `embedded_var_names` are embedded into the comment.
```yaml
embedded_var_names:
- name
```
> feat: add embedded_var_names

- pkg/terraform/template.go
- pkg/terraform/template_test.go
Using HCL syntax for terraform output is easier to read.
Ref: https://github.com/hashicorp/terraform-github-actions/issues/153
> Use HCL syntax

- go.mod
thank you for the good productivity tool.
It seemed that you forget to update go directive 👀 
I just update it below command.
It looks like many diffs but indirect modules are just separated. 
```
$ go mod tidy -go=1.17
```
refs. 
* https://go.dev/ref/mod#go-mod-file-go
* https://zenn.dev/spiegel/articles/20210223-go-module-aware-mode 
※ Japanese blog
> chore: update go directive

- pkg/notifier/github/notify.go
I encountered a problem that the label is not deleted from the pull request that has many labels (around 100).
Since I haven't met such a situation, I expected it's caused by a label append/delete operation.
I found `IssuesListLabels` is calling [ListLabelsByIssue](https://godoc.org/github.com/google/go-github/github#IssuesService.ListLabelsByIssue) function.
https://github.com/suzuki-shunsuke/tfcmt/blob/809b961216eec7a2b6628e61c8ede66929c2691c/pkg/notifier/github/github.go#L37-L40
It calls `GET /repos/{owner}/{repo}/issues/{issue_number}/labels` internally.
The doc is here: https://docs.github.com/en/rest/reference/issues#labels
`per_page` parameter is defaulted to 30, and it seems the root cause of this.
This endpoint have pagination parameter, but a issue / pull request can have 100 …
> Fix not removing stale labels if there are too many labels in the pull request

- pkg/cli/app.go
- pkg/cli/var.go
- pkg/config/config.go
- pkg/controller/controller.go
- pkg/notifier/github/client.go
- pkg/notifier/github/comment.go
- pkg/notifier/github/github.go
- pkg/notifier/github/notify.go
#199
The option `-patch` is added to `tfcmt plan` command.
```console
tfcmt plan -patch -- terraform plan -no-color
```
⚠️ `tfcmt apply` doesn't support patching. We think the comment of `terraform apply` shouldn't be patched.
If the comment isn't patched expectedly, please set `-log-level=debug`.
```console
$ tfcmt -log-level=debug plan -patch -- terraform plan -no-color
```
If you hide comments with [github-comment hide](https://suzuki-shunsuke.github.io/github-comment/hide),
you have to update the condition to prevent the comment of `tfcmt plan` being hidden.
e.g.
```yaml
hide:
default: |
Comment.HasMeta && Comment.Meta.SHA1 != Commit.SHA1 && Comment.Meta.Program != "tfcmt"
```
> Support patching comment in `tfcmt plan`

- pkg/cli/var.go
- pkg/config/config.go
- pkg/controller/controller.go
https://github.com/suzuki-shunsuke/tfcmt/issues/199 Follow up #245
Support configuring tfcmt plan's patch in configuration file
```yaml
plan_patch: true
```
The command line option `-patch` takes precedence over configuration file option `plan_patch`.
If you want to disable patching although `plan_patch` is true, please set `-patch=false`.
```console
$ tfcmt plan -patch=false -- terraform plan -no-color
```
> feat: add the configuration option `plan_patch`

- pkg/controller/apply.go
- pkg/controller/plan.go
This change allows you to run `terraform apply` without `-auto-approve` option.
```console
tfcmt apply -- terraform apply -no-color
null_resource.foo: Refreshing state... [id=8966706083595703589]
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "null_resource" "bar" {
+ id = (known after apply)
}
Plan: 1 to add, 0 to change, 0 to destroy.
Do you want to perform these actions?
Terraform will perform the actions described above.
Only 'yes' will be accepted to approve.
Enter a value: 
Error: error asking for approval: EOF
```
```
Do you want to perform these actions?
Terraform will perform the actions described above.
Only 'yes' will be …
```
> fix: set os.Stdin when terraform command is run

- pkg/notifier/github/apply.go
- pkg/notifier/github/commits.go
- pkg/notifier/github/commits_test.go
- pkg/notifier/github/plan.go
Since GitHub no longer shows commit comments in the pull request timeline [^1], it needs to find a PR associated with a commit in a push event and then post a PR comment if found in order to show comments in the pull request timeline.
See https://github.com/suzuki-shunsuke/tfcmt/issues/387 for more details.
[^1]: github.blog/changelog/2022-08-04-commit-comments-no-longer-appear-in-the-pull-request-timeline
> feat: support PR comments for push events

- pkg/platform/ci.go
Thanks to provide awesome tool!
I noticed the link domain at comment is wrong when I use tfcmd with GitHub Enterprise Server.
GitHub Actions provides default environment variables, so I modified code to use it.
ref; https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
> fix: github actions CI link domain

- pkg/notifier/github/apply.go
- pkg/notifier/github/plan.go
https://github.com/suzuki-shunsuke/tfcmt/blob/fc4a6c08b78b0b240c6a1d340f8c9a23807101a1/pkg/notifier/github/plan.go#L31-L33
Labels aren't set, because PR.IsNumber() is false.
tfcmt should get an associated pull request before adding pull request labels.
> fix: get an associated pull request number before adding pull request labels

- README.md
This PR aims to close https://github.com/suzuki-shunsuke/tfcmt/issues/98 with a mere reference to the GL counterpart.
> chore: add tfmct-gitlab reference to README

- pkg/config/config.go
- pkg/controller/controller.go
This Pull Request implementes https://github.com/suzuki-shunsuke/tfcmt/issues/623.
This feature will help the case when the user wants to add labels only for specific result e.g. adding label for plan error only.
> feat: Add `disable_label` config per result type

- pkg/notifier/localfile/output.go
If the file already exist, the file content is overwritten.
If the file already exist, the file content is appended.
If you prefer the behavior of `AS IS`, please [make the file empty](https://www.tecmint.com/empty-delete-file-content-linux/).
e.g.
```console
: > plan.md
tfcmt --output plan.md plan -- terraform plan
```
> fix(localfile): append the output to a file instead of overwriting

- pkg/cli/app.go
- pkg/cli/var.go
- pkg/config/config.go
- pkg/controller/controller.go
- pkg/notifier/github/client.go
- pkg/notifier/github/plan.go
- https://github.com/suzuki-shunsuke/tfcmt/discussions/773
--
- Add a command line option `-skip-no-changes` to the subcommand `plan`
- Add a field `disable_comment` to the configuration file
e.g.
```console
$ tfcmt plan -skip-no-changes -- terraform plan
```
```yaml
terraform:
plan:
when_no_changes:
disable_comment: true
```
> feat: support skipping no changes

- pkg/notifier/github/plan.go
- pkg/terraform/parser.go
- pkg/terraform/template.go
Parse the output of `terraform plan` and extract moved resources.
e.g.
```tf
```
Add the template variable `MovedResources`, which is a list of moved resources.
e.g.
```yaml
MovedResources:
- Before: null_resource.foo
After: null_resource.bar
```
Add the list of moved resources to the built in template `updated_resources`.
```
* Move
* null_resource.foo => null_resource.bar
```
<pre><code>Plan: 0 to add, 0 to change, 0 to destroy.</code></pre>
* Move
* null_resource.foo => null_resource.bar
<details><summary>Change Result (Click me)</summary>
```hcl
resource "null_resource" "bar" {
id = "4394414639163400357"
}
Plan: 0 to add, 0 to change, 0 to destroy.
```
</details>
> feat: add moved resources to changed resources

- pkg/terraform/parser.go
- pkg/terraform/parser_test.go
Close #117
Related PR: https://github.com/mercari/tfnotify/pull/109
> fix: parse error when only outputs is changed

- pkg/controller/apply.go
- pkg/controller/plan.go
- pkg/notifier/github/apply.go
- pkg/notifier/github/notify_test.go
- pkg/notifier/github/plan.go
- pkg/notifier/localfile/apply.go
- pkg/notifier/localfile/plan.go
- pkg/notifier/notifier.go
The exit code of tfcmt should be same with the original command.
> refactor: stop returning the exit code

- pkg/terraform/parser.go
Follow up https://github.com/suzuki-shunsuke/tfcmt/pull/903
main.tf
```tf
resource "github_repository" "tfcmt" {
name           = "tfcmt"
default_branch = "main" # Deprecated field
}
```
```sh
terraform plan
```
```tf
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "github_repository" "tfcmt" {
+ allow_auto_merge            = false
+ allow_merge_commit          = true
+ allow_rebase_merge          = true
+ allow_squash_merge          = true
+ archived                    = false
+ default_branch              = "main"
+ delete_branch_on_merge      = false
+ etag                        = (known after apply)
+ full_name …
```
> fix: support paring warnings without `-no-color`

- pkg/terraform/parser.go
- https://github.com/suzuki-shunsuke/tfcmt/discussions/955
> feat: support OpenTofu

- pkg/terraform/template.go
When triple backticks are in results for terraform command, wrapCode method uses HTML tags(pre + code) to escape it. But currently these tags are also escaped so it doesn't work as intended.
This PR fixes the bug by
- When triple backticks are not in results, use triple backticks
- When only triple backticks are in results and triple tilde not in results, use triple tilde
- When both triple backticks and triple tilde are in results, use pre + code tags without HTML escape
> Fix fenced code blocks

- go.mod
- go.sum
- pkg/apperr/error.go
- pkg/cli/var.go
- pkg/config/config.go
- pkg/controller/apply.go
- pkg/controller/controller.go
- pkg/controller/plan.go
- pkg/mask/parser.go
- pkg/mask/writer.go
- pkg/notifier/github/apply.go
- pkg/notifier/github/client.go
- pkg/notifier/github/plan.go
- pkg/notifier/localfile/apply.go
- pkg/notifier/localfile/client.go
- pkg/notifier/localfile/plan.go
- https://github.com/suzuki-shunsuke/tfcmt/discussions/1083
> feat: support masking secrets

- pkg/apperr/error.go
- pkg/apperr/error_test.go
Close #1187
This pull request changes the exit code of tfcmt when an error happens.
The exit code was same with the exit code of `terraform plan` and `terraform apply`.
This means tfcmt might have exited with zero even if tfcmt failed to post a comment due to some reason such as API rate limit.
This was not a bug but a expected behavior.
But this behaviour was dangerous because people might have missed unexpected changes.
So this pull request changes the behaviour as tfcmt exits with non zero if any error such as API rate limit happens.
> fix: exit commands with non zero exit code if plan or apply fails

- pkg/cli/app.go
- pkg/cli/var.go
Added a command line option `-disable-label` and an environment variable `TFCMT_DISABLE_LABEL`. If they are set, `tfcmt plan` doesn't set labels.
Close #1290
```sh
tfcmt plan -disable-label -- terraform plan
```
```sh
export TFCMT_DISABLE_LABEL=true
tfcmt plan -- terraform plan
```
> feat(plan): support disabling labels by a command line option and environment variable

- pkg/controller/apply.go
- pkg/controller/plan.go
`tfcmt plan` and `tfcmt apply` require command to be executed.
```sh
tfcmt plan -- terraform plan
tfcmt apply -- terraform apply
```
So this pull request adds a validation if command is specified.
If no command is specified, tfcmt plan and apply return an error immediately.
```console
$ tfcmt plan
ERRO[0000] tfcmt failed                                  error="no command specified"
```
> fix: validate if command is specified

- pkg/cli/var.go
Get GitHub API endpoints from environment variables `GITHUB_API_URL` and `GITHUB_GRAPHQL_URL`, which are GitHub Actions built-in environment variables.
> feat: get GitHub API endpoints from environment variables in GitHub Actions

- pkg/cli/app.go
- pkg/cli/var.go
- pkg/config/config.go
- pkg/controller/controller.go
- pkg/notifier/github/client.go
- pkg/notifier/github/plan.go
Add the option `-ignore-warning` to the `tfcmt plan` command.
By default, tfcmt emphasizes the warning of `terraform plan`, and the option `-skip-no-changes` is ignored if `terraform plan` outputs warning.
This is because we think warning should not be ignored.
But actually we're aware that some users ignore warning normally and they feel warning is noisy.
In this case, it's desirable that `tfcmt plan -skip-no-changes` doesn't post a comment even if warning is outputted.
So this pull request introduces a new option `-ignore-warning`.
If `terraform plan` outputs warning, this option makes the template variable `.Warning` empty, removing the warning from the default template.
If `terraform plan -skip-no-changes` has no change and outputs warning, this option disables to post a comment.
> feat(plan): add the option `-ignore-warning`

- pkg/cli/app.go
```console
$ tfcmt -v
tfcmt version 4.14.4-0 (43ea3601c17774ca5dd239925705dc9f0f281828)
$ tfcmt version
tfcmt 4.14.4-0 (43ea3601c17774ca5dd239925705dc9f0f281828)
```
Hmm. `version` is missing, but this is not so problem. 😅
> fix: fix version command
