suzuki-shunsuke/tfcmt

- README.md
- main.go
- notifier/github/notify.go
- notifier/github/notify_test.go
- notifier/notifier.go
- terraform/parser.go
- terraform/parser_test.go
BREAKING CHANGE: the command interface is changed
> feat: accepts command instead of stdin

- COMPARED_WITH_TFNOTIFY.md
- main.go
BREAKING CHANGE: remove notifier option
only GitHub is supported
> feat: remove notifier option

- COMPARED_WITH_TFNOTIFY.md
- config/config.go
- main.go
- notifier/github/notify.go
BREAKING CHANGE: label is set by default
> feat: add config disable_label

- main.go
> fix: fix default no change label

- COMPARED_WITH_TFNOTIFY.md
* avoidHTMLEscape
* wrapCode
Follow up #42
> docs: add description about template functions

- COMPARED_WITH_TFNOTIFY.md
- main.go
https://github.com/suzuki-shunsuke/ci-info
> feat: support to get a pull request number from CI_INFO_PR_NUBER

- terraform/template.go
- terraform/template_test.go
Add ✅  and :x: to comment title to make the result clear
> feat: improve default template

- .cmdx.yaml
https://github.com/suzuki-shunsuke/cmdx
> chore: add config of cmdx

- .goreleaser.yml
we update release note manually before releasing
> chore(goreleaser): configure prerelease true

- pkg/terraform/parser.go
> feat: support Terraform v0.15

- docs/CONFIGURATION.md
> docs: add document about ChangeOutsideTerraform etc

- README.md
> docs: add aqua to install section

- pkg/terraform/template.go
#227
I've implemented the proposal 2. https://github.com/suzuki-shunsuke/tfcmt/issues/227#issuecomment-1080129167
> feat: omit too long message automatically

- README.md
> docs: add a link to document source repository

- pkg/notifier/github/notify.go
> fix: check metadata's Command in patch

- pkg/notifier/github/notify.go
Fix the bug that comments of `tfcmt apply` patch comments of `tfcmt plan`.
> fix: patch comment for tfcmt apply

- pkg/notifier/github/commits.go
- pkg/notifier/github/commits_test.go
> refactor: remove ListCommits API

- pkg/notifier/github/commits.go
- pkg/notifier/github/commits_test.go
- pkg/notifier/github/github.go
- pkg/notifier/github/github_test.go
> feat: get the associated pull request with commit

- pkg/config/config.go
- pkg/controller/controller.go
- pkg/notifier/github/client.go
https://github.com/suzuki-shunsuke/tfcmt/issues/300#issuecomment-1136548324
Follow up https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v3.2.0
e.g.
```yaml
ghe_graphql_endpoint: https://api.github.com/graphql
```
> fix: support GitHub API v4 for GitHub Enterprise

- go.mod
- go.sum
- pkg/config/config.go
- pkg/platform/ci.go
- pkg/platform/google_cloud_build.go
Please set the environment variable `GOOGLE_CLOUD_BUILD`.
```sh
GOOGLE_CLOUD_BUILD=true
```
And please set the following environment variables using [substitutions](https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values).
* `COMMIT_SHA`
* `BUILD_ID`
* `PROJECT_ID`
* `_PR_NUMBER`
* `_REGION`
Please specify the repository owner and name in `tfcmt.yaml`.
e.g.
tfcmt.yaml
```yaml
repo_owner: suzuki-shunsuke
repo_name: tfcmt
```
> feat: support Google Cloud Build

- examples/getting-started/README.md
> fix url of the getting started page

- .github/workflows/release.yaml
- .github/workflows/test.yaml
- aqua.yaml
- pkg/config/config.go
- pkg/config/config_test.go
https://github.com/suzuki-shunsuke/tfcmt/pull/363
> chore: update Go to v1.19.1 and golangci-lint to v1.49.0

- .github/workflows/actionlint.yaml
- .github/workflows/test-main.yaml
- .github/workflows/test.yaml
- .golangci.yml
- aqua-checksums.json
- aqua.yaml
- aqua/actionlint.yaml
- aqua/cmdx.yaml
- aqua/cosign.yaml
- aqua/ghcp.yaml
- aqua/golangci-lint.yaml
- aqua/reviewdog.yaml
- renovate.json5
https://github.com/aquaproj/example-update-checksum-public
> ci: automerge pull requests from Renovate

- aqua-checksums.json
- aqua/goreleaser.yaml
https://github.com/suzuki-shunsuke/go-release-workflow/releases/tag/v0.2.0
> ci: install GoReleaser by aqua

- .github/workflows/actionlint.yaml
https://github.com/suzuki-shunsuke/actionlint-workflow/pull/19
> ci: test actionlint-workflow#19

- .github/workflows/test.yaml
- https://github.com/suzuki-shunsuke/go-test-full-workflow/pull/37
> ci: test go mod tidy

- pkg/cli/app.go
- pkg/cli/apply.go
- pkg/cli/plan.go
- pkg/cli/var.go
- TFCMT_REPO_OWNER
- TFCMT_REPO_NAME
- TFCMT_SHA
- TFCMT_PR_NUMBER
- TFCMT_CONFIG
- TFCMT_VAR_*
> feat: support passing command line arguments via environment variables

- pkg/terraform/parser.go
- https://github.com/suzuki-shunsuke/tfcmt/discussions/823
> fix: fix summary of tainted resources

- pkg/terraform/parser.go
Close https://github.com/suzuki-shunsuke/tfcmt/issues/829
> fix: support terraform's `-replace` option

- pkg/notifier/github/plan.go
- pkg/terraform/parser.go
- pkg/terraform/template.go
Close #882
Parse the output of `terraform plan` and extract imported resources.
e.g.
```tf
```
Add the template variable `ImportedResources`, which is a list of imported resources.
e.g.
```yaml
ImportedResources:
- github_repository.tfcmt
```
Add the list of imported resources to the built in template `updated_resources`.
```
* Import
* github_repository.tfcmt
```
<pre><code>Plan: 1 to import, 0 to add, 0 to change, 0 to destroy.</code></pre>
* Import
* github_repository.tfcmt
<details><summary>Change Result (Click me)</summary>
```hcl
resource "github_repository" "tfcmt" {
allow_auto_merge            = true
allow_merge_commit          = true
allow_rebase_merge          = true
allow_squash_merge          = true
allow_update_branch         = true
archived                    = false …
```
> feat: add imported resources to the list of changed resources

- pkg/notifier/localfile/plan.go
Follow up #881 and #884
https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v4.5.0
> fix(localfile): list moved and imported resources

- pkg/terraform/template.go
Follow up https://github.com/suzuki-shunsuke/tfcmt/pull/906
> fix: pass HasError to template

- pkg/terraform/parser.go
- pkg/terraform/parser_test.go
- https://github.com/suzuki-shunsuke/tfcmt/discussions/930
Before
```
* Create
* null_resource.zoo
* Update
* github_repository.tfaction-2
* github_repository.tfcmt
* Replace
* github_issue.test-2
* Move
* null_resource.foo => null_resource.bar
```
After
```
* Create
* null_resource.zoo
* Update
* github_repository.tfaction-2
* github_repository.tfcmt
* Replace
* github_issue.test-2
* Import
* github_repository.tfcmt
* Move
* github_issue.test => github_issue.test-2
* github_repository.tfaction => github_repository.tfaction-2
* null_resource.foo => null_resource.bar
```
> feat: listing imported or moved resources even if they are changed or replaced

- README.md
Maybe useful, since there is a small trend of changing licenses these days.
> README: minor updates to be precise on previous license

- README.md
ref. https://github.com/suzuki-shunsuke/tfcmt/discussions/1032#discussioncomment-7677699
> docs: Add Cybozu Engineering Productivity Team to who-uses-tfcmt

- example-with-destroy-and-result-labels.tfcmt.yaml
- pkg/config/config_test.go
- pkg/terraform/template.go
- https://github.com/suzuki-shunsuke/tfcmt/issues/1061#issuecomment-1846276851
> fix: remove emojis from the end of lines

- README.md
> docs: Add READYFOR Platform Team to who-uses-tfcmt

- pkg/config/config.go
- pkg/controller/controller.go
- pkg/notifier/github/client.go
- pkg/notifier/github/client_test.go
- pkg/notifier/github/comment_test.go
- pkg/notifier/github/commits_test.go
- pkg/notifier/github/github_test.go
- pkg/notifier/github/notify_test.go
> feat: support the environment variable TFCMT_GITHUB_TOKEN

- README.md
> docs: Add CADDi to who-uses-tfcmt

- README.md
> add: ZOZO Inc. in README.md

- README.md
refs -> https://github.com/suzuki-shunsuke/tfcmt/discussions/1032#discussioncomment-8599376
> docs: append SAKURA internet Inc. to who-uses-tfcmt

- README.md
ref https://github.com/suzuki-shunsuke/tfcmt/discussions/1032
> docs: append Unipos Inc. to who-uses-tfcmt in README.md

- README.md
ref https://github.com/suzuki-shunsuke/tfcmt/discussions/1032
Thank you for the cool OSS. We always use it usefully :)
> docs: append paild, Inc. in README.md

- .github/pull_request_template.md
> docs: fix pull request template

- go.mod
- pkg/apperr/error_test.go
- pkg/config/config_test.go
- pkg/notifier/github/client_test.go
- pkg/notifier/github/comment_test.go
- pkg/notifier/github/notify_test.go
- pkg/terraform/parser_test.go
> refactor: update go directive

- pkg/cli/app.go
Follow up #1257
- Link to the issue:
- This repository enables `Require signed commits`, so all commits must be signed
> fix: set ExitErrHandler

- .github/workflows/test-main.yaml
- .github/workflows/watch-star.yaml
https://github.com/suzuki-shunsuke/batch-bulk-ghatm/issues/1
> ci: set timeout-minutes using ghatm

- go.mod
- go.sum
> feat: post comments to pull request via GitHub Actions' merge_group event

- pkg/terraform/template.go
- https://github.com/suzuki-shunsuke/tfcmt/issues/1363
> feat: add the warning when the content is omitted

- README.md
See https://github.com/hmcts/cnp-azuredevops-libraries/blob/4d67de7239e2d87de7c40d2e315f44c47502ac1d/steps/terraform.yaml#L194
- Link to the issue:
- This repository enables `Require signed commits`, so all commits must be signed
> Add HMCTS to users of tfcmt

- pkg/cli/app.go
- TFCMT_PLAN_PATCH
- TFCMT_SKIP_NO_CHANGES
- TFCMT_IGNORE_WARNING
> feat(plan): bind some environment variables to options

- README.md
- Link to the issue: https://github.com/suzuki-shunsuke/tfcmt/discussions/1032
- This repository enables `Require signed commits`, so all commits must be signed
Thank you for creating such a great open-source project!
> docs: add LayerX to who-uses-tfcmt

- .github/workflows/test.yaml
- .golangci.yml
- aqua/aqua-checksums.json
- aqua/imports/golangci-lint.yaml
- pkg/config/config_test.go
- pkg/notifier/github/client_test.go
- pkg/notifier/github/github.go
- https://github.com/suzuki-shunsuke/batch-task/issues/7
> chore: Migrate golangci-lint to v2

- README.md
> docs: add Section-9 to who-uses-tfcmt

- README.md
> docs: add H2O Retailing Corp. to who-uses-tfcmt

- .github/workflows/actionlint.yaml
- .github/workflows/autofix.yaml
- .github/workflows/test.yaml
- https://github.com/suzuki-shunsuke/batch-task/issues/14
> ci: Fix if: failure() of GitHub Actions

- .goreleaser.yml
- https://github.com/suzuki-shunsuke/ghalint/issues/966
> chore: fix Homebrew tap to remove the quarantine bit from the binary on a post install hook

- README.md
- Link to the issue:
- This repository enables `Require signed commits`, so all commits must be signed
Thanks for mentioning the blog post! tfcmt was really helpful.
> docs: add ENECHANGE to who-uses-tfcmt
